site_name: Faerlin's Portfolio
site_url: https://mydomain.org/mysite
theme:
  name: material
  palette:
    primary: black
  icon:
    logo: fontawesome/solid/atom
    repo: fontawesome/brands/git-alt
  favicon: assets/favicon.ico
  font:
    text: Lora

repo_url: https://github.com/faerlin-developer/portfolio
repo_name: faerlin-developer/portfolio

nav:
  - About: index.md
  - Projects:
      - Fractal Animation Server: fractal-animation-server.md
      - Kanban Board with React: kanban-board-react.md
      - Path Finding Algorithms: path-finding-algorithms.md
      - N-Body Simulation: n-body.md

extra:
  generator: false

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

plugins:
  - glightbox

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - css/extra.css